### ISSUE TITLE
Někdy nefugují linky u Billy

### ISSUE THREAD

**Issue by xsuchy** [xsuchy/heissepreise-cz#10]
Zkusil jsem vyhledat "mýdlo" u Billy a kliknout na výrobek. Ze tří pokusů dva pokusy hlásili výrobek nenalezen.

**Comment by xsuchy** [comment]
Hmm, tam kde to nefuguje se jedná o stará data - ze září. Takže ten výrobek už asi opravdu nemají. Akorát nevím co s tím... aby to bylo user friendly.

**Comment by eltomjan** [comment]
https://github.com/xsuchy/heissepreise-cz/blob/a5e9c23728b2302894945cf9c59b652f65f0987e/site/model/stores.js#L5-L9
getUrl: (item) => (item.url ? \`https://shop.billa.cz/produkt/${item.url}` : <b>\`https://www.google.com/search?q="${item.id}"`</b>),

Zkusil jsem vyhodit href, ale nestačilo; tak co google třeba by pomohl...
