### ISSUE TITLE
Chybějící Billa kategorie blokuje download.

### ISSUE THREAD

**Issue by eltomjan** [xsuchy/heissepreise-cz#14]
https://github.com/xsuchy/heissepreise-cz/blob/6e7d82b917c102baa8217d1cd1f712e926affefb/stores/billa.js#L10-L11
Už je po vánocích, takže 404 a exception se vysype až do 

https://github.com/xsuchy/heissepreise-cz/blob/6e7d82b917c102baa8217d1cd1f712e926affefb/analysis.js#L317-L320

**Comment by xsuchy** [comment]
Opraveno v
* f64083e oprava Billy, kdyz je chybna kategorie
* 3b299fb odstranit docasnou kategoriz billy
