### ISSUE TITLE
Zprovoznění DM

### ISSUE THREAD

**Issue by xsuchy** [xsuchy/heissepreise-cz#4]
Je třeba zprovoznit DM a nastavit české adresy https://github.com/xsuchy/heissepreise-cz/blob/main/stores/dm.js

**Comment by eltomjan** [comment]
Have working version, but no rights to push them.

Btw found 2 problems in original before switching:
allCategories.id=010000&price.value.from=10&price.value.to=15 **1085** vs 1000 limit
allCategories.id=060000&price.value.to=4 **1080**

**Comment by xsuchy** [comment]
Hotovo
