### ISSUE TITLE
Zprovozneni Albertu

### ISSUE THREAD

**Issue by xsuchy** [xsuchy/heissepreise-cz#5]
API je popsano v kapitole 5.2 teto prace https://k00.fr/cdp3ctxj

**Comment by eltomjan** [comment]
https://www.albert.cz/api/v1/?operationName=LeftHandNavigationBar&variables={"rootCategoryCode":"","cutOffLevel":"4","lang":"cs"}&extensions={"persistedQuery":{"version":1,"sha256Hash":"..."}}
[->AlbertCats.json](https://github.com/xsuchy/heissepreise-cz/files/13741529/AlbertCats.json)

Drogerie example:
https://www.albert.cz/api/v1/?operationName=GetCategoryProductSearch&variables={"lang":"cs","searchQuery":"","category":"zeBV01","pageNumber":0,"pageSize":20,"filterFlag":true,"plainChildCategories":true}&extensions={"persistedQuery":{"version":1,"sha256Hash":"..."}}

https://www.albert.cz/api/v1/?operationName=GetCategoryProductSearch&variables={"lang":"cs","searchQuery":"","category":"zeBB01","pageNumber":0,"pageSize":20,"filterFlag":true,"plainChildCategories":true}&extensions={"persistedQuery":{"version":1,"sha256Hash":"..."}}

**deviceSessionIdKey (CORS / albert.cz - 1st script of https://www.albert.cz/online):**
```
window.mapi = {
    getDeviceId: () => ((graphqlEndpoint, deviceSessionIdKey) => {
  const operationName = 'DeviceId';
  const params = {
    method: 'POST',
    body: JSON.stringify({
      query: `query ${operationName} {deviceId}`
    }),
    headers: {
      'Content-Type': 'application/json',
      'X-Apollo-Operation-Name': operationName
    },
    credentials: 'include'
  }
  return fetch(graphqlEndpoint, params).then(response => response.json()).then(json => {
    const {
      deviceId
    } = json.data;
    localStorage.setItem(deviceSessionIdKey, deviceId);
    return deviceId;
  }).catch(() => null);
})("https://www.albert.cz/api/v1/","deviceSessionId"),
  };
  window.mapi.getDeviceId();
```

**Params:**
```
deviceSessionIdKey: "deviceSessionId"
graphqlEndpoint: "https://www.albert.cz/api/v1/"
operationName: "DeviceId"

params = {method: 'POST', body: '{"query":"query DeviceId {deviceId}"}', 'headers': {
  'Content-Type': 'application/json',
  'X-Apollo-Operation-Name': 'DeviceId'
}, 'credentials': 'include'}
```

**Comment by eltomjan** [comment]
> API je popsano v kapitole 5.2 teto prace https://k00.fr/cdp3ctxj

Pracuju na tom, byly tam nějaké SHA-256, ale už to zdá se čte, teď už jen probrat ty JSON-y a přemapovat je :-)

P.S.: https://www.albert.cz/_next/static/chunks/8471-a8e5dd9cf28187df.js tady se to šifrovalo (od ř. 16155):
```
    37503: function(e, t, n) {
        "use strict";
        const r = "undefined" !== typeof globalThis ? globalThis : "undefined" !== typeof self ? self : "undefined" !== typeof window ? window : "undefined" !== typeof n.g ? n.g : void 0
          , i = e=>async(t,n)=>{
            "string" === typeof t && (t = (new r.TextEncoder).encode(t)),
            n = {
                outputFormat: "hex",
                ...n
            };
            const i = await r.crypto.subtle.digest(e, t);
            return "hex" === n.outputFormat ? (e=>{
                const t = new DataView(e);
                let n = "";
                for (let r = 0; r < t.byteLength; r += 4)
                    n += t.getUint32(r).toString(16).padStart(8, "0");
                return n
            }
            )(i) : i
        }
        ;
        i("SHA-1"),
        t.JQ = i("SHA-256"),
        i("SHA-384"),
        i("SHA-512")
    },

```

**Comment by eltomjan** [comment]
Hotovo, ale asi nemá smysl vytvářet PR, protože by nešel oddělit od toho DM(?)

**Comment by xsuchy** [comment]
Tohle je hotove.
