### ISSUE TITLE
Zprovozneni Globusu

### ISSUE THREAD

**Issue by xsuchy** [xsuchy/heissepreise-cz#6]
API je popsano v kapitole 5.3 teto prace https://k00.fr/cdp3ctxj

**Comment by eltomjan** [comment]
https://webcache.googleusercontent.com/search?q=cache:l2DUuQqS2P8J:https://uuapp.plus4u.net/uu-webkit-maing02/27b98c6535cf4e16b697849c7da33c9f/binary/getData%3Fslot%3Dprod2%26code%3Dsmall_globusen&hl=en&gl=cz

https://webcache.googleusercontent.com/search?q=cache:l2DUuQqS2P8J:https://uuapp.plus4u.net/uu-webkit-maing02/27b98c6535cf4e16b697849c7da33c9f/binary/getData%3Fslot%3Dprod2%26code%3Dsmall_globusen&hl=en&gl=cz&strip=1&vwsrc=0

IIS seems to be on that URL, but REST API returns 404, anyway found mention of possible authors(?)

Or there are action pages in APP, but seems to be separate for each branch:
https://www.globusbonus.cz/nabidka/?HouseNumber=4005&do=setLocalization	Praha - Čakovice
https://www.globusbonus.cz/nabidka/?HouseNumber=4002&do=setLocalization	Praha - Černý Most
https://www.globusbonus.cz/nabidka/?HouseNumber=4003&do=setLocalization	Praha - Zličín
https://www.globusbonus.cz/nabidka/?HouseNumber=4026&do=setLocalization	Praha - Štěrboholy
https://www.globusbonus.cz/nabidka/?HouseNumber=4001&do=setLocalization	Brno
https://www.globusbonus.cz/nabidka/?HouseNumber=4009&do=setLocalization	České Budějovice
https://www.globusbonus.cz/nabidka/?HouseNumber=4019&do=setLocalization	Havířov
https://www.globusbonus.cz/nabidka/?HouseNumber=4010&do=setLocalization	Chomutov
https://www.globusbonus.cz/nabidka/?HouseNumber=4014&do=setLocalization	Karlovy Vary - Jenišov
https://www.globusbonus.cz/nabidka/?HouseNumber=4006&do=setLocalization	Liberec
https://www.globusbonus.cz/nabidka/?HouseNumber=4008&do=setLocalization	Olomouc
https://www.globusbonus.cz/nabidka/?HouseNumber=4012&do=setLocalization	Opava
https://www.globusbonus.cz/nabidka/?HouseNumber=4007&do=setLocalization	Ostrava
https://www.globusbonus.cz/nabidka/?HouseNumber=4004&do=setLocalization	Pardubice
https://www.globusbonus.cz/nabidka/?HouseNumber=4011&do=setLocalization	Plzeň - Chotíkov
https://www.globusbonus.cz/nabidka/?HouseNumber=4015&do=setLocalization	Trmice

globus.cz uses different API like:
https://gapi.globus.cz/OnlineAsset/3/asset?assetID=...

Found some JSON in Actions/Next like:
[https.../api/v1/gsoa/actionOffers/houses/4005/actionProductsCatalog?<br>filter=categoryId:in 1&listedProductOnly=false&blickPunkt=false&page=1&pageSize=16](https://www.globus.cz/api/v1/gsoa/actionOffers/houses/4005/actionProductsCatalog?filter=categoryId:in%201&listedProductOnly=false&blickPunkt=false&page=1&pageSize=16)

Categories (1-24):
|Category|ID|URL|
|---|---|---|
|Čerstvé potraviny|1|....globus.cz/api/v1/gsoa/actionOffers/houses/4005/actionProductsCatalog?...
|Trvanlivé potraviny|2|
|(N/A)|3|
|Pečivo|4|
|Maso, uzeniny|5|
|(N/A)|6-9|
|Ostatní|10|
|(N/A)|11|(404) filter=categoryId:in 11...|
|Dům, zahrada|12|
|:-)|13|(404) filter=categoryId:in 13...|
|Alkoholické nápoje|14|filter=categoryId:in&nbsp;14&listedProductOnly=false&blickPunkt=false&page=0&pageSize=16|
|Nealkoholické nápoje|15|filter=categoryId:in 15&listedProductOnly=false&blickPunkt=false&page=0&pageSize=16|
|Lahůdky|16|filter=categoryId:in 16&listedProductOnly=false&blickPunkt=false&page=0&pageSize=16|
|Mražené|17|filter=categoryId:in 17&listedProductOnly=false&blickPunkt=false&page=0&pageSize=16|
|Drogerie|18|filter=categoryId:in 18&listedProductOnly=false&blickPunkt=false&page=0&pageSize=16|
|Domácnost|19|filter=categoryId:in 19&listedProductOnly=false&blickPunkt=false&page=0&pageSize=16|
|Zábava a volný čas|20|filter=categoryId:in 20&listedProductOnly=false&blickPunkt=false&page=0&pageSize=16|
|Elektro|21|filter=categoryId:in 21&listedProductOnly=false&blickPunkt=false&page=0&pageSize=16|
|Móda|22|filter=categoryId:in 22&listedProductOnly=false&blickPunkt=false&page=0&pageSize=16|
|Vlastní výroba|23|filter=categoryId:in 23&listedProductOnly=false&blickPunkt=false&page=0&pageSize=16|
|Zdravý svět|24|filter=categoryId:in 24&listedProductOnly=false&blickPunkt=false&page=0&pageSize=16|

**Comment by xsuchy** [comment]
> A co jinak - hloubám nad tím globusem - vybrat nějakou pobočku nebo načíst všechny a pak nějak volit, které hodnoty jsou ty správné ??

Mergování těch prodejen bude peklo. Hlavně se rozhodovat co je správné. Takže bych se na to vykašlal a načítal jenom jednu prodejdu. První prodejna Globusu byla ta v Brně a myslím, že je stále největší? Je některá větší? Nebo spíš - má některá prodejna v tom seznamu nejvíce položek? Tu bych pak vybral a tahal data jenom z ní.

**Comment by eltomjan** [comment]
Tak klasicky 2. commit v PR - tentokrát v Albertu...
https://github.com/xsuchy/heissepreise-cz/pull/9/commits/2e9e5b3d147a13e07122f8e395b04f51f55f8d70
Jsou dost podobné, Brno toho asi má nejvíc hned po Zličínu (počet položek) a spousta jich nemá kategorii vlastní výroba (23), což je označeno i v kódu:

const shops = [
        4001, //4002, 4003, 4004, 4005, /*!23>*/**4006, 4007, 4008, 4009, 4010, 4011, 4012, 4014**/*<!23*/, 4015, /*!23>*/**4019, 4026**
    ];
A když jsem jich načítal víc, při změně to někdy ukončilo spojení(?), takže by asi čtení z více ani nefungovalo, mimochodem uvádí i počet skladem :-) a URL chybí, tak ho zkouším generovat, ale občas to nefunguje - např. taková _Gemerka Botanica Meduňka 1,5L_ - skladem je - stockAmount: 1164, minimumPresentationStock: 26, ale nenašel jsem ji ani ručně na webu ??
https://shop.iglobus.cz/cz/n%C3%A1poje/nealkoholick%C3%A9-n%C3%A1poje/vody-a-miner%C3%A1lky/jemn%C4%9B-perliv%C3%A9?sort=name_desc
Možná není na netu, ale jen v brně(?), ale nefunkčních linků je víc...

**Comment by xsuchy** [comment]
Hotovo.
